### ISSUE TITLE
Worth fixing this month mapping error too?

### ISSUE THREAD

**Issue by trepmal** [michaeluno/_fix-simplepie-errors#1]
https://github.com/michaeluno/_fix-simplepie-errors/blob/8db3d89df0741554fe0b664f749b438a3165ccc8/include/SimplePie/Parse/Date.php#L176

upstream fix is here: https://github.com/simplepie/simplepie/commit/be4f0f7a89bd2ded1bf1fa5722ff0bf62d62e742

**Comment by michaeluno** [comment]
Will do. Thank you.
